# Generated by Django 4.2.4 on 2023-08-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_entry', models.CharField(max_length=250)),
                ('word_def', models.TextField()),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='images/vocal/')),
                ('examples', models.TextField()),
                ('thesaurus', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
