# Generated by Django 4.2.4 on 2023-08-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voca',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='images/voca/'),
        ),
    ]
